### ISSUE TITLE
Error when running update all

### ISSUE THREAD

**Issue by greysilly7** [Neocky/pluGET#17]
**Describe the bug**

**To Reproduce**
1. Luanch using SFTP
2. type "check all"
3. type "update all"

**Expected behavior**
It to update plugins

**Screenshots**
![image](https://user-images.githubusercontent.com/65827291/113790876-5e29ca00-9710-11eb-96e2-4873c01aaac2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
`Traceback (most recent call last):
  File "C:\Users\greys\Downloads\pluGET\src\__main__.py", line 16, in <module>
    mainFunction()
  File "C:\Users\greys\Downloads\pluGET\src\__main__.py", line 14, in mainFunction
    getInput()
  File "C:\Users\greys\Downloads\pluGET\src\handlers\handle_input.py", line 105, in getInput
    handleInput(inputCommand, inputSelectedObject, inputParams)
  File "C:\Users\greys\Downloads\pluGET\src\handlers\handle_input.py", line 87, in handleInput
    getInput()
  File "C:\Users\greys\Downloads\pluGET\src\handlers\handle_input.py", line 105, in getInput
    handleInput(inputCommand, inputSelectedObject, inputParams)
  File "C:\Users\greys\Downloads\pluGET\src\handlers\handle_input.py", line 58, in handleInput
    updateInstalledPackage(inputSelectedObject)
  File "C:\Users\greys\Downloads\pluGET\src\plugin\plugin_updatechecker.py", line 266, in updateInstalledPackage
    if INSTALLEDPLUGINLIST[i][3] == True:
IndexError: list index out of range`

**Comment by Neocky** [comment]
Hey,
thank you for your bug report.
I will investigate the issue and will report back. 
Stay tuned!

**Comment by Neocky** [comment]
Hey @greysilly7,
i just releases a new version which fixes your problem: [v1.5.1](https://github.com/Neocky/pluGET/releases/tag/v1.5.1)
The numbers should also be correctly shown.
Update to the new version and you are good to go.

### Thank you for flying with pluGET 🚀

**Comment by greysilly7** [comment]
Thanks
