### ISSUE TITLE
Doesn't work with some file names.

### ISSUE THREAD

**Issue by Levakiv** [Neocky/pluGET#23]
Describe the bug

If in file name contain "-symbol(s).symbol(s)-", it causes the program to crash.

To Reproduce
1 Create a file with name contain "-symbol(s).symbol(s)-", for example: ["InvisibleItemFrame_***-1.0-***_SNAPSHOT](https://www.spigotmc.org/resources/invisibleitemframe.81303/download?version=343272)".
2 Launch "pluGET"
3 Use "check all"
4 See error: `Traceback (most recent call last):
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\__main__.py", line 16, in <module>
    mainFunction()
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\__main__.py", line 14, in mainFunction
    getInput()
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\handlers\handle_input.py", line 105, in getInput
    handleInput(inputCommand, inputSelectedObject, inputParams)
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\handlers\handle_input.py", line 86, in handleInput
    getInput()
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\handlers\handle_input.py", line 105, in getInput
    handleInput(inputCommand, inputSelectedObject, inputParams)
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\handlers\handle_input.py", line 64, in handleInput
    checkInstalledPackage(inputSelectedObject)
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\plugin\plugin_updatechecker.py", line 138, in checkInstalledPackage
    pluginId = getInstalledPlugin(fileName, fileVersion, plugin)
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\plugin\plugin_updatechecker.py", line 362, in getInstalledPlugin
    packageName = doAPIRequest(url)
  File "C:\Users\egorg\Desktop\Новая папка\tet\src\utils\web_request.py", line 8, in doAPIRequest
    packageDetails = response.json()
  File "C:\Users\egorg\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\egorg\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\egorg\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\egorg\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Screenshots:
![bandicam 2021-05-27 20-32-26-204](https://user-images.githubusercontent.com/68151306/119871109-cf287980-bf2a-11eb-9948-975581073b43.jpg)

OS: windows 10 home build 19041

**Comment by Neocky** [comment]
Hey @Levakiv,

i just updated pluGET to version 1.5.5 which fixes your issue. Download it [here](https://github.com/Neocky/pluGET/releases/tag/1.5.5).  
Update to the latest version and you are good to go. 😃 

### Thank you for flying with pluGET 🚀

**Comment by Levakiv** [comment]
> Hey @Levakiv,
> 
> i just updated pluGET to version 1.5.5 which fixes your issue. Download it [here](https://github.com/Neocky/pluGET/releases/tag/1.5.5).
> Update to the latest version and you are good to go. 😃
> 
> ### Thank you for flying with pluGET 🚀

Problems fixed only for ".jar" files. Files .zip  and other files (not .jar) still cause crashes, if in file name contain "-symbol(s).symbol(s)-" or "-symbol(s).".

zip:![zip](https://user-images.githubusercontent.com/68151306/120071911-e8036d00-c099-11eb-8848-d609c87e930c.jpg)
other files ![txt](https://user-images.githubusercontent.com/68151306/120071898-df129b80-c099-11eb-9b5d-3fcfaa5fe1af.jpg)

**Comment by Neocky** [comment]
Hey @Levakiv,
thank you very much for your testings!
I already committed a fix to the main branch wich will skip all files which are not .jar files. This will fix the issues.
Download it here: https://github.com/Neocky/pluGET/archive/3ad77536744a8ea144abb6c4ffb6eb2d98522ea4.zip

Or you can wait for an official update which i will later release! 😃

**Comment by Neocky** [comment]
Fixed in [v.1.5.6](https://github.com/Neocky/pluGET/releases/tag/1.5.6)
Download it and you are good to go!

### Thanks again for flying with pluGET 🚀
