### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by keldnorman** [Neocky/pluGET#46]
pluGET >> get essentialsx
Searching: essentialsx
┌─────┬─────────────────────────────┬───────────┬──────────────────────────────────────────────────────────────────────┐
│ No. │ Name                        │ Downloads │ Description                                                          │
└─────┴─────────────────────────────┴───────────┴──────────────────────────────────────────────────────────────────────┘
   [1]  EssentialsX                     4352274   The essential plugin suite for Minecraft servers, now updated for Paper and Spigot 1.18.1                               
   [2]  EssentialsXGUIBanner              12275   A Nice GUI Temp-banning Plugin Alike The One Used On The Performium Server!                                             
   [3]  BkTeleport                         3632   Teleport countdown on screen, Chat clickable TPA and TPHERE, GUI for homes and warps and more!                          
   [4]  KitPreviewEssentialsxaddon         3128   Essentialsx addon                                                                                                       
   [5]  iWarp                               760   Player warps expire unless expressly renewed                                                                            
   [6]  [U] - uSleep >> EssentialsX & SuperVanish Support [1.14 - 1.16]      581   A simple plugin that will change the way you sleep, custom percentage, AFK and Vanish support.                          
   [7]  EssentialsXExtras                   198   Add cool features to your server.                                                                                       
   [8]  EssentialsXYZ                       178   A plugin for ease of use and admin.                                                                                     
   [9]  EssentialsXLite                     173   An alternative(not really) to Essentials, with performance in mind!                                                     
  [10]  EssentialsXAntiMSGSpam              164   Blocks /msg spam!                                                                                                       
Select your wanted resource (No.)(0 to exit): 1
File is  None
Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
    mainFunction()
  File "__main__.py", line 14, in mainFunction
    getInput()
  File "/root/source/pluGET/pluGET/src/handlers/handle_input.py", line 105, in getInput
    handleInput(inputCommand, inputSelectedObject, inputParams)
  File "/root/source/pluGET/pluGET/src/handlers/handle_input.py", line 52, in handleInput
    searchPackage(inputSelectedObject)
  File "/root/source/pluGET/pluGET/src/plugin/plugin_downloader.py", line 94, in searchPackage
    getSpecificPackage(resourceId, pluginDownloadPath)
  File "/root/source/pluGET/pluGET/src/plugin/plugin_downloader.py", line 151, in getSpecificPackage
    downloadSpecificVersion(resourceId=resourceId, downloadPath=downloadPackagePath)
  File "/root/source/pluGET/pluGET/src/plugin/plugin_downloader.py", line 117, in downloadSpecificVersion
    filesize = int(filesize)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by ryanpag3** [comment]
Seems like the spigot API isn't sending the `Content-Length` header back that the script uses to calculate file sizes and print out the result.

https://github.com/Neocky/pluGET/blob/50759226748f3e53e36406b14cc55f82ba800dd5/src/plugin/plugin_downloader.py#L116-L123

I just decided to comment out those lines for now as I don't really care about the print statement as long as it doesn't error.
