### ISSUE TITLE
Error: Couldn't Parse JSON

### ISSUE THREAD

**Issue by Cpd879** [Neocky/pluGET#78]
**Error: Couldn't parse json of webrequest
**

**To Reproduce**
1. Install a lot of plugins. Maybe 50+
2. Run It (check all)

**Expected behavior**
Expected it to update all.
TIP = It works if I specify a plugin. EG - check EssentialsX

OS - Linux Debian (Raspberry Pi 5)

**Additional context**
Full Error Log
=>
Error: Couldn't parse json of webrequest
Traceback (most recent call last):
  File "/home/Cpd879/pluGET/pluget.py", line 45, in <module>
    handle_input()
  File "/home/Cpd879/pluGET/src/handlers/handle_input.py", line 85, in handle_input
    check_installed_plugins(input_selected_object, input_parameter)
  File "/home/Cpd879/pluGET/src/plugin/plugin_updatechecker.py", line 341, in check_installed_plugins
    plugin_count, plugins_with_udpates = check_update_available_installed_plugins(input_selected_object, config_values)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Cpd879/pluGET/src/plugin/plugin_updatechecker.py", line 316, in check_update_available_installed_plugins
    plugin_spigot_id = search_plugin_spiget(plugin_file, plugin_file_name, plugin_file_version) # plugin_spigot_id isn't needed
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Cpd879/pluGET/src/plugin/plugin_updatechecker.py", line 555, in search_plugin_spiget
    for plugin in plugin_list:
TypeError: 'NoneType' object is not iterable

**Comment by Neocky** [comment]
### Hey @Cpd879,

this issue got most likely fixed in [v1.8.0](https://github.com/Neocky/pluGET/releases/tag/v1.8.0).
If it isn't yet I will need a full plugin list.
Have a nice day!

**Comment by Cpd879** [comment]
Thanks @Neocky!, I will try again after some time
